name:                 cswk-program
version:              0.1.0.0
visibility:           public
id:                   cswk-program-0.1.0.0-KQEWBwkUvHwEJnNJbtWf11
key:                  cswk-program-0.1.0.0-KQEWBwkUvHwEJnNJbtWf11
abi:                  ff7e27a4748b8f33d00b47e4d50cea00
exposed:              True
exposed-modules:      Game Visuals Window
hidden-modules:       Paths_cswk_program
import-dirs:
    /home/joe/2048/2-lambda/.stack-work/install/x86_64-linux-tinfo6/cc58021b69f5cae06b1e4d79d0230d9a2f4e583cea28d8cad0b6cc5c486120b9/8.10.7/lib/x86_64-linux-ghc-8.10.7/cswk-program-0.1.0.0-KQEWBwkUvHwEJnNJbtWf11

library-dirs:
    /home/joe/2048/2-lambda/.stack-work/install/x86_64-linux-tinfo6/cc58021b69f5cae06b1e4d79d0230d9a2f4e583cea28d8cad0b6cc5c486120b9/8.10.7/lib/x86_64-linux-ghc-8.10.7/cswk-program-0.1.0.0-KQEWBwkUvHwEJnNJbtWf11

dynamic-library-dirs:
    /home/joe/2048/2-lambda/.stack-work/install/x86_64-linux-tinfo6/cc58021b69f5cae06b1e4d79d0230d9a2f4e583cea28d8cad0b6cc5c486120b9/8.10.7/lib/x86_64-linux-ghc-8.10.7

data-dir:
    /home/joe/2048/2-lambda/.stack-work/install/x86_64-linux-tinfo6/cc58021b69f5cae06b1e4d79d0230d9a2f4e583cea28d8cad0b6cc5c486120b9/8.10.7/share/x86_64-linux-ghc-8.10.7/cswk-program-0.1.0.0

hs-libraries:         HScswk-program-0.1.0.0-KQEWBwkUvHwEJnNJbtWf11
depends:
    base-4.14.3.0 gloss-1.13.2.1-D0DWqwqH5FM7COJ90qifNp
    random-1.2.0-GAV679NMk7iDELNoxF99p4

haddock-interfaces:
    /home/joe/2048/2-lambda/.stack-work/install/x86_64-linux-tinfo6/cc58021b69f5cae06b1e4d79d0230d9a2f4e583cea28d8cad0b6cc5c486120b9/8.10.7/doc/cswk-program-0.1.0.0/cswk-program.haddock

haddock-html:
    /home/joe/2048/2-lambda/.stack-work/install/x86_64-linux-tinfo6/cc58021b69f5cae06b1e4d79d0230d9a2f4e583cea28d8cad0b6cc5c486120b9/8.10.7/doc/cswk-program-0.1.0.0
